### ISSUE TITLE
possible to share a mini readme section?

### ISSUE THREAD

**Issue by geokal** [meinlebenswerk/openapi2django#1]
Hi thanks for sharing your project. Am trying to understand how can I use it , especially the serializer part. Is it disabled by default or does it work on par with the bosyserializer? Also do you thinks it’s possible with some additional code to customize it for models generation? Thanks in advance!

**Comment by meinlebenswerk** [comment]
Sure, I'm currently swamped with exams, but I could get around to making a short writeup, if I can remeber how the tool works ;)
But as far as I remember, serializers seemed to be too complex to get working easily and they're broken currently, which is why they're disabled.

**Comment by geokal** [comment]
Hope the best for you ! I wiil try to play around with your code eventually ! the models and sterilizers would be very promising! browsing github for some days, there are no such implementation , the only close project is [OpenAlchemy] (https://github.com/jdkandersson/OpenAlchemy) for Flask and sqalchemy with Connexion module.

**Comment by meinlebenswerk** [comment]
I just added a quick writeup of how and why this project came to be, and how to use it.
If you have any further questions, don't hesitate to write another comment :)
